### ISSUE TITLE
Plots only giving the best fit

### ISSUE THREAD

**Issue by sarahnicholas** [jklynch/mr-fitty#1]
Dear Josh,
Now when I use mr-fitty it only gives me the best-fit plot in the pdf, where it used to give me the second-best and best for 1, 2 and 3 component fits (6 plots per fitted spectrum).  Can I have them back?  
warm regards,
Sarah

**Comment by jklynch** [comment]
The number of best-fit plots for each component count can now be specified in the configuration file from the new  (required) `[plots]` section.
```
[plots]
best_fits_plot_limit = 3
```
