### ISSUE TITLE
more significant figures for NSS in fits tables?

### ISSUE THREAD

**Issue by sarahnicholas** [jklynch/mr-fitty#5]
Hey there, Could we have more significant figures in the NSS in the fits tables?
Warm regards,
Sarah

**Comment by sarahnicholas** [comment]
Also, could the NSS be displayed in the figures?
Thank you,
Sarah

**Comment by jklynch** [comment]
Create a new issue!

**Comment by jklynch** [comment]
You will now find more decimal places reported for NSS in the fit table.
